// <auto-generated />
namespace FigureMvcWebApi.Model.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateIsIntersectFunction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateIsIntersectFunction));
        
        string IMigrationMetadata.Id
        {
            get { return "202406240855101_CreateIsIntersectFunction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
